spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://user:password@localhost:27017/db?authSource=admin
telegram:
  bot:
    token: '6141569812:AAF5VsG74Tt-DeOAphfWMjaDsYCars8L6Ow'
    username: '@aviabooking_bot'